name: 'GCP Workflows Advanced Actions'
description: 'Help to deploy Cloud Functions used by a Workflow'
author: 'Yohann PARISIEN'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  env:
    description: 'Environment (dev/staging/prod)'
    required: true
    default: 'dev'
  specs:
    description: 'Specifications of Workflow'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
